title: Arthur Vanderbilt
tagline: Personal commonplace and hypomnema.
email: aav@aav.me
description: The personal commonplace and hypomnema of Arthur Vanderbilt.
url: "http://aav.me"
twitter_username: arthur
github_username:  avanderbilt
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
